# This file created by conda-build 2.0.0beta
# meta.yaml template originally from:
# /home/ilan/anaconda/packages/conda-env, last modified Fri Jun 17 00:31:57 2016
# ------------------------------------------------

package:
    name: conda-env
    version: 2.5.1
source:
    git_rev: v2.5.1
    git_url: https://github.com/conda/conda-env.git
build:
    entry_points:
        - conda-env = conda_env.cli.main:main
requirements:
    build:
        - python
    run:
        - python
about:
    description: 'Provides the conda env interface to Conda environments. All of the
        usage

        is documented via the --help flag.

        '
    dev_url: https://github.com/conda/conda-env/
    doc_url: http://conda.pydata.org/docs/
    home: https://github.com/conda/conda-env/
    license: BSD
    license_file: LICENSE.txt
    summary: Provides a unified interface to dealing with Conda environments
